repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      entry: docker-compose run --rm processing black .
      args: [--safe]
      language_version: python3.6
